language: cpp
compiler: gcc
sudo: require
dist: trusty

install:
  - sudo apt-get -y install wget libncurses5-dev libncursesw5-dev gcc libsdl1.2-dev

script:
  - wget http://syncterm.bbsdev.net/syncterm-src.tgz
  - tar xvzf syncterm-src.tgz
  - cd syncterm-*/src/syncterm
  - st_path=$(pwd | sed 's/\/syncterm$//g')
  - sudo make SRC_ROOT=$st_path
  - sudo make install
  - mkdir -p appdir/usr/bin ; cp ../../src/syncterm/gcc.linux.x64.exe.debug/syncterm appdir/usr/bin/
  - strip appdir/usr/bin/syncterm
  - mkdir -p appdir/usr/share/applications ; cp ../../src/syncterm/syncterm.desktop appdir/usr/share/applications/
  - mkdir -p appdir/usr/share/icons/hicolor/64x64/ ; cp syncterm.png appdir/usr/share/icons/hicolor/64x64/

  - find appdir/
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh SyncTERM*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
